/**
 * Reflection pipeline — the "dreaming" phase that generates deeper insights
 * from episodic memories after consolidation.
 *
 * Unlike consolidation (which extracts facts and preferences), reflection
 * finds causal chains, recurring patterns, counterfactuals, and
 * self-assessments across episodes.  It runs post-consolidation when
 * enough episodes exist, rate-limited to once per 4 hours.
 */

import type { Database } from "./schema.js";
import { type Episode, rowToEpisode } from "./episodes.js";
import { saveSemanticNote, searchByEmbedding, saveNoteEmbedding } from "./semantic.js";

import { nowISO, repairAndParseJSON } from "./utils.js";
import { log } from "../../logger.js";
import { resolveKnowledgeThreadId } from "../../config.js";
import { getThread } from "./thread-registry.js";
import {
  chatCompletion,
  generateEmbedding,
  type ChatMessage,
} from "../../integrations/openai/chat.js";
import { errorMessage } from "../../utils.js";

// ─── Types ───────────────────────────────────────────────────────────────────

interface ReflectionInsight {
  type: "causal" | "pattern" | "self_assessment" | "counterfactual";
  content: string;
  confidence: number;
  relatedEpisodeIds: string[];
}

interface ReflectionResult {
  insights: ReflectionInsight[];
  processedEpisodeCount: number;
  duration: number;
}

// ─── Rate-limiting ───────────────────────────────────────────────────────────

const REFLECTION_COOLDOWN_MS = 4 * 60 * 60 * 1000; // 4 hours
const MIN_EPISODES_FOR_REFLECTION = 20;

// ─── Buffer cap & quality gate ───────────────────────────────────────────────
const MAX_ACTIVE_REFLECTIONS = 75;
const STALE_REFLECTION_DAYS = 30;
const MIN_INSIGHT_LENGTH = 50;
const VAGUE_PATTERNS = [
  /\bthe agent tends to\b/i,
  /\bI tend to\b/i,
  /\bthe agent demonstrates\b/i,
  /\bthe agent frequently\b/i,
  /\bshould consider\b/i,
  /\bthis (is|was) (a |an )?(good|important|useful)\b/i,
  /\bin general\b/i,
  /\boverall\b.*\b(good|well|effective)\b/i,
  /\bthe key (insight|takeaway|lesson) is\b/i,
  /\bit('s| is) important to\b/i,
  /\bthis (led|leads) to\b(?!\s+\w{4,})/i,
  /\bgoing forward\b/i,
  /\bmoving forward\b/i,
  /\ba? ?valuable (lesson|experience|insight)\b/i,
  /\bI (learned|realized|recognized|acknowledged) that\b/i,
  /\bthis (highlights|underscores|demonstrates)\b/i,
  /\bsignificant (progress|strides|developments?|evolution)\b/i,
  /\bnotable improvements?\b/i,
  /\bvarious features\b/i,
  /\bseveral enhancements\b/i,
  /\bI regularly (review|conduct|perform|check)\b/i,
  /\bI frequently (create|manage|handle)\b/i,
];

const BANNED_TOPIC_PATTERNS = [
  /\bmemory (system|audit|cleanup|quality|consolidat)/i,
  /\bconsolidation (process|pipeline|prompt)\b/i,
  /\breflection (quality|pipeline|system)\b/i,
  /\bdeduplication\b/i,
  /\bnote (archival|cleanup|expir)/i,
  /\bI (conducted|scheduled|implemented) a (memory|cleanup|audit)\b/i,
];

// Domain tags are freeform short labels (1-2 words) generated by the LLM.

/** Per-thread timestamp of the last successful reflection run. */
const lastReflectionAt = new Map<number, number>();
/** Per-thread guard against concurrent reflection runs. */
const reflectionInProgress = new Set<number>();

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Extract text from an episode's content object. */
function episodeText(ep: Episode): string {
  const c = ep.content;
  if (typeof c === "string") return c;
  return (c.text as string) ?? (c.caption as string) ?? JSON.stringify(c);
}

/** Build a time-ordered narrative from a list of episodes. */
function buildNarrative(episodes: Episode[]): string {
  return episodes
    .sort((a, b) => a.timestamp.localeCompare(b.timestamp))
    .map((ep) => `[${ep.episodeId}] (${ep.type}/${ep.modality}, ${ep.timestamp}) ${episodeText(ep)}`)
    .join("\n");
}

/** Gather consolidated episodes: last N recent + random sample of older ones. */
function gatherEpisodes(
  db: Database,
  threadId: number,
  maxRecent: number,
  oldSampleSize: number,
): Episode[] {
  // Recent consolidated episodes
  const recentRows = db
    .prepare(
      `SELECT * FROM episodes
       WHERE thread_id = ? AND consolidated = 1
       ORDER BY timestamp DESC
       LIMIT ?`,
    )
    .all(threadId, maxRecent) as Record<string, unknown>[];

  const recentIds = new Set(recentRows.map((r) => r.episode_id as string));

  // Random sample of older consolidated episodes from the past 7 days
  // (excluding the ones already in the recent set)
  const olderRows = db
    .prepare(
      `SELECT * FROM episodes
       WHERE thread_id = ? AND consolidated = 1
         AND timestamp >= datetime('now', '-7 days')
       ORDER BY RANDOM()
       LIMIT ?`,
    )
    .all(threadId, oldSampleSize + recentRows.length) as Record<string, unknown>[];

  const olderFiltered = olderRows
    .filter((r) => !recentIds.has(r.episode_id as string))
    .slice(0, oldSampleSize);

  const allRows = [...recentRows, ...olderFiltered];
  return allRows.map(rowToEpisode);
}


// ─── Prompt ──────────────────────────────────────────────────────────────────

const REFLECTION_ANALYZE_PROMPT = `You are a reflective reasoning system analyzing your own recent experiences. Your job is to think deeply and freely — no templates, no JSON, no structured output.

Analyze the episodes for patterns, cause-effect chains, mistakes, recurring situations, and missed opportunities. Write in first person ("I"). Produce 2-3 paragraphs of genuine free-form reasoning. Focus on WHY things happened, not just WHAT happened. Dig into root causes and underlying mechanisms.

## BANNED topics — do NOT analyze:
- The memory system, consolidation, audits, cleanup, deduplication, or memory quality
- The agent's own internal operations or meta-processes
- How the agent manages its own notes, reflections, or knowledge base
- Only reflect on EXTERNAL work: the project, codebase, operator interactions, technical decisions.`;

const REFLECTION_STRUCTURE_PROMPT = `You are a reflective reasoning system. You will receive a free-form analysis and the original episodes it was based on. Your job is to extract the top 3-5 insights from the analysis into a structured format.

For each insight, you MUST fill in ALL 5 template fields. If the analysis does not support filling every field with specific, concrete information, SKIP that insight entirely. Do not produce vague filler.

## Template fields (ALL required):

1. **decision** — What specific action or choice was made? Name the exact thing that happened.
2. **context** — What was the situation that triggered this? What were the conditions?
3. **outcome** — What was the concrete result? Was it positive or negative? Be specific.
4. **root_cause** — WHY did this outcome happen? This must NOT restate the outcome. Dig deeper. What was the actual mechanism?
5. **lesson** — A concrete, executable instruction for next time. Start with a verb: "Always...", "Never...", "Before doing X, first..."

## Task domain (required):

Classify each insight with a short freeform domain tag (1-2 words, kebab-case). Examples: debugging, linkedin-strategy, memory-system, hiring, content-marketing, architecture. Pick whatever fits the topic naturally.

## Insight types:

- "causal": cause-effect chains — "When [X], it led to [Y] because [Z]"
- "pattern": recurring behaviors or situations
- "counterfactual": what could have been done differently
- "self_assessment": strengths and weaknesses

Respond in JSON format:
{
  "insights": [
    {
      "type": "causal" | "pattern" | "self_assessment" | "counterfactual",
      "decision": "The specific action taken",
      "context": "What triggered it",
      "outcome": "What happened as a result",
      "root_cause": "The underlying WHY",
      "lesson": "Concrete instruction for next time",
      "domain": "short-kebab-case-tag",
      "confidence": 0.0-1.0,
      "episode_refs": ["ep_xxx", "ep_yyy"]
    }
  ]
}

## Anti-patterns (your output WILL BE REJECTED if it contains these):

- "The agent tends to..." / "I tend to..." — vague observation, not actionable
- "Should consider..." — wishy-washy, not a concrete instruction
- "In general..." / "Overall..." / "significant progress" / "notable improvements" — too abstract
- "various features" / "several enhancements" / "multiple improvements" — unspecific
- Restating the outcome as the root cause
- Lesson that doesn't start with a verb
- Any field shorter than 10 characters

Rules:
- Minimum 1, maximum 5 insights — prefer fewer, deeper insights
- Each insight must reference specific episodes by their ID (from the original episodes provided)
- Confidence should reflect how well-supported the insight is by evidence
- Causal insights are most valuable — prioritize cause-and-effect
- Quality over quantity: 2 deep insights beat 5 shallow ones
- Return {"insights": []} if the analysis does not support any deep insights`;

// ─── De-duplication ──────────────────────────────────────────────────────────

const DEDUP_SIMILARITY_THRESHOLD = 0.90;
const LESSON_DEDUP_THRESHOLD = 0.82;

async function checkDuplicate(
  db: Database,
  content: string,
  apiKey: string,
  threadId: number,
): Promise<{ isDuplicate: boolean; embedding: Float32Array | null }> {
  try {
    const embedding = await generateEmbedding(content, apiKey);
    const matches = searchByEmbedding(db, embedding, {
      maxResults: 3,
      minSimilarity: DEDUP_SIMILARITY_THRESHOLD,
      skipAccessTracking: true,
      threadId,
    });
    const isDuplicate = matches.some(
      (m) => m.similarity >= DEDUP_SIMILARITY_THRESHOLD && m.content.startsWith("[REFLECTION]"),
    );
    return { isDuplicate, embedding };
  } catch (err) {
    log.warn(`[reflection] Dedup embedding lookup failed: ${errorMessage(err)}`);
    // Embedding lookup failed — allow the insight through to avoid data loss
    return { isDuplicate: false, embedding: null };
  }
}

/**
 * Lesson-level dedup: checks if a semantically similar lesson already exists
 * among reflection notes using a lower similarity threshold (0.82).
 * Catches generic lessons like "Always do comprehensive code reviews" that are
 * worded differently but carry the same meaning.
 */
async function checkLessonDuplicate(
  db: Database,
  lesson: string,
  apiKey: string,
  knowledgeThreadId: number,
): Promise<boolean> {
  try {
    const embedding = await generateEmbedding(lesson, apiKey);
    const matches = searchByEmbedding(db, embedding, {
      maxResults: 3,
      minSimilarity: LESSON_DEDUP_THRESHOLD,
      skipAccessTracking: true,
      threadId: knowledgeThreadId,
    });
    if (matches.some((m) => m.similarity >= LESSON_DEDUP_THRESHOLD && m.content.startsWith("[REFLECTION]"))) {
      return true;
    }
    return false;
  } catch (err) {
    log.warn(`[reflection] Lesson dedup embedding lookup failed: ${errorMessage(err)}`);
    // Embedding lookup failed — allow through to avoid data loss
    return false;
  }
}

// ─── Quality gate ────────────────────────────────────────────────────────────

/** Check if an insight passes the quality gate (actionable, specific, non-vague, non-meta). */
export function passesQualityGate(content: string, confidence: number): { pass: boolean; reason?: string } {
  if (content.length < MIN_INSIGHT_LENGTH) {
    return { pass: false, reason: "too short" };
  }
  if (confidence < 0.3) {
    return { pass: false, reason: "confidence too low" };
  }
  for (const pattern of VAGUE_PATTERNS) {
    if (pattern.test(content)) {
      return { pass: false, reason: `matches vague pattern: ${pattern.source}` };
    }
  }
  for (const pattern of BANNED_TOPIC_PATTERNS) {
    if (pattern.test(content)) {
      return { pass: false, reason: `banned topic: ${pattern.source}` };
    }
  }
  return { pass: true };
}

/** Parse reflection content into structured fields. Returns null if parsing fails. */
export function parseReflectionFields(content: string): {
  decision: string;
  context: string;
  outcome: string;
  root_cause: string;
  lesson: string;
} | null {
  const decisionMatch = content.match(/Decision:\s*(.+?)(?:\s*Context:|$)/s);
  const contextMatch = content.match(/Context:\s*(.+?)(?:\s*Outcome:|$)/s);
  const outcomeMatch = content.match(/Outcome:\s*(.+?)(?:\s*Root cause:|$)/s);
  const rootCauseMatch = content.match(/Root cause:\s*(.+?)(?:\s*Lesson:|$)/s);
  const lessonMatch = content.match(/Lesson:\s*(.+?)(?:\s*$)/s);

  if (!decisionMatch || !lessonMatch) return null;

  return {
    decision: decisionMatch[1]?.trim() ?? "",
    context: contextMatch?.[1]?.trim() ?? "",
    outcome: outcomeMatch?.[1]?.trim() ?? "",
    root_cause: rootCauseMatch?.[1]?.trim() ?? "",
    lesson: lessonMatch[1]?.trim() ?? "",
  };
}

/** Validate structural integrity of parsed insight fields. */
export function passesStructuralGate(insight: {
  decision: string;
  context: string;
  outcome: string;
  root_cause: string;
  lesson: string;
}): { pass: boolean; reason?: string } {
  // Check root_cause is meaningfully different from outcome (skip for very short fields)
  const outcomeWords = new Set(insight.outcome.toLowerCase().replace(/[.,:;!?]/g, "").split(/\s+/).filter(w => w.length > 3));
  const rootWords = new Set(insight.root_cause.toLowerCase().replace(/[.,:;!?]/g, "").split(/\s+/).filter(w => w.length > 3));
  if (outcomeWords.size >= 3) {
    const overlap = [...outcomeWords].filter(w => rootWords.has(w)).length;
    const overlapRatio = overlap / outcomeWords.size;
    if (overlapRatio > 0.6) {
      return { pass: false, reason: "root_cause restates outcome" };
    }
  }

  // Check lesson starts with a verb (actionable)
  const lessonStart = insight.lesson.trim().split(/\s/)[0]?.toLowerCase() ?? "";
  const actionVerbs = ["always", "never", "before", "after", "when", "if", "check", "verify", "ensure", "use", "avoid", "run", "test", "add", "remove", "set", "create", "implement", "review", "validate", "confirm", "monitor", "track", "log", "document", "separate", "isolate", "prefer", "prioritize", "consider", "evaluate", "compare", "measure", "schedule", "watch", "build", "configure", "enable", "define", "wrap", "cache", "query", "disable", "expose", "update", "read", "write", "fetch", "parse", "handle", "keep", "limit", "require", "include", "exclude", "apply", "deploy", "migrate", "start", "stop"];
  if (!actionVerbs.some(v => lessonStart.startsWith(v))) {
    return { pass: false, reason: "lesson does not start with an action verb" };
  }

  // Check minimum field lengths (more strict than the 10-char check elsewhere)
  if (insight.root_cause.length < 30) {
    return { pass: false, reason: "root_cause too shallow (< 30 chars)" };
  }
  if (insight.lesson.length < 20) {
    return { pass: false, reason: "lesson too short (< 20 chars)" };
  }

  return { pass: true };
}

/** Expire stale reflections (>30 days old, never accessed) and enforce buffer cap. */
function enforceReflectionCap(db: Database, threadId: number): { expired: number } {
  const knowledgeThreadId = resolveKnowledgeThreadId(threadId);
  let expired = 0;

  // Phase 1: Expire stale never-accessed reflections
  const staleResult = db
    .prepare(
      `UPDATE semantic_notes
       SET valid_to = ?
       WHERE valid_to IS NULL AND superseded_by IS NULL
         AND content LIKE '[REFLECTION]%'
         AND access_count = 0
         AND created_at < datetime('now', '-' || ? || ' days')
         AND (thread_id = ? OR thread_id IS NULL)`,
    )
    .run(nowISO(), STALE_REFLECTION_DAYS, knowledgeThreadId);
  expired += staleResult.changes;

  // Phase 2: Enforce hard cap — if still over limit, expire lowest-value
  const countRow = db
    .prepare(
      `SELECT COUNT(*) as c FROM semantic_notes
       WHERE valid_to IS NULL AND superseded_by IS NULL
         AND content LIKE '[REFLECTION]%'
         AND (thread_id = ? OR thread_id IS NULL)`,
    )
    .get(knowledgeThreadId) as { c: number };

  if (countRow.c > MAX_ACTIVE_REFLECTIONS) {
    const excess = countRow.c - MAX_ACTIVE_REFLECTIONS;
    const toExpire = db
      .prepare(
        `SELECT note_id FROM semantic_notes
         WHERE valid_to IS NULL AND superseded_by IS NULL
           AND content LIKE '[REFLECTION]%'
           AND pinned = 0 AND is_guardrail = 0
           AND (thread_id = ? OR thread_id IS NULL)
         ORDER BY access_count ASC, created_at ASC
         LIMIT ?`,
      )
      .all(knowledgeThreadId, excess) as { note_id: string }[];

    if (toExpire.length > 0) {
      const now = nowISO();
      const stmt = db.prepare(`UPDATE semantic_notes SET valid_to = ? WHERE note_id = ?`);
      db.transaction(() => {
        for (const row of toExpire) stmt.run(now, row.note_id);
      })();
      expired += toExpire.length;
    }
  }

  if (expired > 0) {
    log.info(`[reflection] Buffer maintenance: expired ${expired} stale/excess reflections`);
  }
  return { expired };
}

// ─── Core Pipeline ───────────────────────────────────────────────────────────

/**
 * Run the reflection pipeline on recent consolidated episodes.
 * Generates deeper insights beyond simple fact/preference extraction.
 *
 * Pipeline:
 *   1. Gate check — enough episodes, rate limit, API key present
 *   2. Gather episodes — recent + random sample of older ones
 *   3. Build a narrative from episode content
 *   4. Send to OpenAI with the reflection prompt
 *   5. Parse insights, de-duplicate, and save as semantic notes
 */
export async function runReflection(
  db: Database,
  threadId: number,
  options?: { maxEpisodes?: number; includeOldSample?: boolean },
): Promise<ReflectionResult> {
  const startMs = Date.now();
  const maxRecent = options?.maxEpisodes ?? 30;
  const oldSampleSize = options?.includeOldSample !== false ? 10 : 0;

  // ── Gate: worker thread ───────────────────────────────────────────────────
  const threadEntry = getThread(db, threadId);
  if (threadEntry?.type === "worker") {
    log.info(`[reflection] Skipping — thread ${threadId} is a worker thread`);
    return { insights: [], processedEpisodeCount: 0, duration: Date.now() - startMs };
  }

  // ── Gate: rate limit ──────────────────────────────────────────────────────
  const lastRun = lastReflectionAt.get(threadId) ?? 0;
  if (Date.now() - lastRun < REFLECTION_COOLDOWN_MS) {
    log.info("[reflection] Skipped — cooldown not elapsed");
    return { insights: [], processedEpisodeCount: 0, duration: Date.now() - startMs };
  }
  if (reflectionInProgress.has(threadId)) {
    log.info("[reflection] Skipped — already running for this thread");
    return { insights: [], processedEpisodeCount: 0, duration: Date.now() - startMs };
  }
  reflectionInProgress.add(threadId);
  try { return await runReflectionInner(db, threadId, startMs, maxRecent, oldSampleSize); }
  finally { reflectionInProgress.delete(threadId); }
}

async function runReflectionInner(
  db: Database,
  threadId: number,
  startMs: number,
  maxRecent: number,
  oldSampleSize: number,
): Promise<ReflectionResult> {

  // ── Gate: environment ─────────────────────────────────────────────────────
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    log.warn("[reflection] Skipped — OPENAI_API_KEY not set");
    return { insights: [], processedEpisodeCount: 0, duration: Date.now() - startMs };
  }

  const reflectionEnabled = process.env.REFLECTION_ENABLED;
  if (reflectionEnabled === "false" || reflectionEnabled === "0") {
    return { insights: [], processedEpisodeCount: 0, duration: Date.now() - startMs };
  }

  // ── Gate: episode count ───────────────────────────────────────────────────
  const countRow = db
    .prepare("SELECT COUNT(*) as c FROM episodes WHERE thread_id = ? AND consolidated = 1")
    .get(threadId) as { c: number };
  if (countRow.c < MIN_EPISODES_FOR_REFLECTION) {
    log.info(`[reflection] Skipped — only ${countRow.c} consolidated episodes (need ${MIN_EPISODES_FOR_REFLECTION})`);
    return { insights: [], processedEpisodeCount: 0, duration: Date.now() - startMs };
  }

  const knowledgeThreadId = resolveKnowledgeThreadId(threadId);

  // ── Step 0: Buffer maintenance — expire stale, enforce cap ─────────────
  enforceReflectionCap(db, threadId);

  // ── Step 1: Gather episodes ───────────────────────────────────────────────
  const episodes = gatherEpisodes(db, threadId, maxRecent, oldSampleSize);
  if (episodes.length === 0) {
    return { insights: [], processedEpisodeCount: 0, duration: Date.now() - startMs };
  }

  // ── Step 2: Build narrative ───────────────────────────────────────────────
  const narrative = buildNarrative(episodes);

  // ── Step 3a: ANALYZE — free-form reasoning ───────────────────────────────
  const analyzeMessages: ChatMessage[] = [
    { role: "system", content: REFLECTION_ANALYZE_PROMPT },
    { role: "user", content: `## Episodes to analyze:\n${narrative}\n\nAnalyze the episodes above. What patterns, cause-effect chains, mistakes, or recurring situations do you see? Think deeply. Write 2-3 paragraphs of free-form reasoning.` },
  ];

  let analysis: string;
  try {
    analysis = await chatCompletion(analyzeMessages, apiKey, {
      model: process.env.REFLECTION_MODEL ?? process.env.CONSOLIDATION_MODEL ?? "gpt-4o",
      maxTokens: 1500,
      temperature: 0.55,
      timeoutMs: 90_000,
    });
  } catch (err) {
    log.error(`[reflection] Analyze step failed: ${errorMessage(err)}`);
    return { insights: [], processedEpisodeCount: episodes.length, duration: Date.now() - startMs };
  }

  if (!analysis.trim()) {
    log.warn("[reflection] Analyze step returned empty response — skipping structure step");
    return { insights: [], processedEpisodeCount: episodes.length, duration: Date.now() - startMs };
  }

  log.debug(`[reflection] Analyze step complete (${analysis.length} chars): ${analysis.slice(0, 120)}…`);

  // ── Step 3b: STRUCTURE — mechanical formatting ────────────────────────────
  const structureMessages: ChatMessage[] = [
    { role: "system", content: REFLECTION_STRUCTURE_PROMPT },
    { role: "user", content: `## Free-form analysis:\n${analysis}\n\n## Original episodes (for episode_refs):\n${narrative}\n\nExtract the top 3-5 insights from this analysis into the structured JSON format.` },
  ];

  let raw: string;
  try {
    raw = await chatCompletion(structureMessages, apiKey, {
      model: process.env.REFLECTION_MODEL ?? process.env.CONSOLIDATION_MODEL ?? "gpt-4o",
      maxTokens: 4096,
      temperature: 0.25,
      responseFormat: { type: "json_object" },
      timeoutMs: 90_000,
    });
  } catch (err) {
    log.error(`[reflection] Structure step failed: ${errorMessage(err)} — analysis was: ${analysis.slice(0, 200)}`);
    return { insights: [], processedEpisodeCount: episodes.length, duration: Date.now() - startMs };
  }

  // ── Step 4: Parse response ────────────────────────────────────────────────
  let parsed: { insights?: RawInsight[] };
  try {
    parsed = repairAndParseJSON(raw) as { insights?: RawInsight[] };
  } catch (err) {
    log.error(`[reflection] JSON parse failed: ${errorMessage(err)}`);
    return { insights: [], processedEpisodeCount: episodes.length, duration: Date.now() - startMs };
  }

  const rawInsights = parsed.insights ?? [];
  const validTypes = new Set(["causal", "pattern", "self_assessment", "counterfactual"]);

  // ── Step 5: Save insights ─────────────────────────────────────────────────
  const savedInsights: ReflectionInsight[] = [];
  const episodeIdSet = new Set(episodes.map((e) => e.episodeId));

  for (const ins of rawInsights) {
    // Validate all 5 template fields are present and non-trivial
    const fields = [ins.decision, ins.context, ins.outcome, ins.root_cause, ins.lesson];
    if (fields.some((f) => !f || typeof f !== "string" || f.length < 10)) {
      log.info(`[reflection] Skipped — incomplete template fields`);
      continue;
    }

    // Compile structured fields into a single rich content string.
    // Strip trailing punctuation from each field so the ". " separator doesn't
    // produce double periods when the LLM ends a field with its own period.
    const stripTrailing = (s: string) => s.trim().replace(/[.!?]+$/, "");
    const content = [
      `Decision: ${stripTrailing(ins.decision)}`,
      `Context: ${stripTrailing(ins.context)}`,
      `Outcome: ${stripTrailing(ins.outcome)}`,
      `Root cause: ${stripTrailing(ins.root_cause)}`,
      `Lesson: ${stripTrailing(ins.lesson)}`,
    ].join(". ");

    const insightType = validTypes.has(ins.type) ? ins.type : "pattern";
    const confidence = Math.max(0, Math.min(1, ins.confidence ?? 0.5));
    const refs = (ins.episode_refs ?? []).filter((id) => typeof id === "string" && episodeIdSet.has(id));

    // Normalize freeform domain tag
    const domain = (typeof ins.domain === "string" && ins.domain.trim().length > 0)
      ? ins.domain.trim().toLowerCase().slice(0, 30)
      : "general";

    // Quality gate — reject vague/generic insights before expensive dedup
    const quality = passesQualityGate(content, confidence);
    if (!quality.pass) {
      log.info(`[reflection] Quality gate rejected: ${quality.reason} — "${content.slice(0, 60)}…"`);
      continue;
    }

    // Structural gate — reject insights where root_cause restates outcome or lesson is not actionable
    const structural = passesStructuralGate({
      decision: ins.decision,
      context: ins.context,
      outcome: ins.outcome,
      root_cause: ins.root_cause,
      lesson: ins.lesson,
    });
    if (!structural.pass) {
      log.info(`[reflection] Structural gate rejected: ${structural.reason} — "${content.slice(0, 60)}…"`);
      continue;
    }

    // De-duplicate against existing reflections (embedding is cached for reuse)
    const prefixedContent = `[REFLECTION] [${insightType.toUpperCase()}] [${domain}] ${content}`;
    const { isDuplicate: duplicate, embedding: cachedEmbedding } = await checkDuplicate(db, prefixedContent, apiKey, knowledgeThreadId);
    if (duplicate) {
      log.info(`[reflection] Skipped duplicate insight: ${content.slice(0, 60)}…`);
      continue;
    }

    // Lesson-level dedup — catches semantically similar lessons at a lower threshold
    const lessonDuplicate = await checkLessonDuplicate(db, ins.lesson, apiKey, knowledgeThreadId);
    if (lessonDuplicate) {
      log.info(`[reflection] Skipped lesson-level duplicate: "${ins.lesson.slice(0, 60)}…"`);
      continue;
    }

    // Generate keywords from content + add domain as keyword
    const keywords = extractKeywords(content);

    // Save as a semantic note of type "pattern" (reflection insights are patterns)
    const noteId = saveSemanticNote(db, {
      type: "pattern",
      content: prefixedContent,
      keywords: ["reflection", insightType, domain, ...keywords],
      confidence,
      priority: confidence >= 0.8 ? 1 : 0,
      threadId: knowledgeThreadId,
      sourceEpisodes: refs,
    });

    // Reuse the embedding from dedup check — avoids a second API call
    if (cachedEmbedding) {
      saveNoteEmbedding(db, noteId, cachedEmbedding);
    } else {
      try {
        const embedding = await generateEmbedding(prefixedContent, apiKey);
        saveNoteEmbedding(db, noteId, embedding);
      } catch (err) {
        log.debug(`[reflection] Embedding save failed (backfill will retry): ${errorMessage(err)}`);
      }
    }

    savedInsights.push({
      type: insightType as ReflectionInsight["type"],
      content,
      confidence,
      relatedEpisodeIds: refs,
    });
  }

  // ── Log result ────────────────────────────────────────────────────────────
  logReflection(db, {
    episodesProcessed: episodes.length,
    insightsCreated: savedInsights.length,
    durationMs: Date.now() - startMs,
  });

  lastReflectionAt.set(threadId, Date.now());

  log.info(
    `[reflection] Completed: ${episodes.length} episodes → ${savedInsights.length} insights (${Date.now() - startMs}ms)`,
  );

  return {
    insights: savedInsights,
    processedEpisodeCount: episodes.length,
    duration: Date.now() - startMs,
  };
}

// ─── Keyword extraction ──────────────────────────────────────────────────────

const STOP_WORDS = new Set([
  "this", "that", "with", "from", "have", "been", "will", "would", "could",
  "should", "about", "there", "their", "which", "when", "what", "were",
  "they", "than", "then", "also", "just", "more", "some", "into", "over",
  "after", "before", "other", "very", "your", "here", "does", "because",
  "instead", "agent", "operator", "the", "and", "for", "are", "but", "not",
  "you", "all", "can", "had", "her", "was", "one", "our", "out",
]);

/** Extract up to 5 meaningful keywords from free-text content. */
function extractKeywords(text: string): string[] {
  const words = text
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .split(/\s+/)
    .filter((w) => w.length > 3 && !STOP_WORDS.has(w));

  const freq = new Map<string, number>();
  for (const w of words) freq.set(w, (freq.get(w) ?? 0) + 1);

  return [...freq.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([w]) => w);
}

// ─── Consolidation log ───────────────────────────────────────────────────────

function logReflection(
  db: Database,
  entry: { episodesProcessed: number; insightsCreated: number; durationMs: number },
): void {
  db.prepare(
    `INSERT INTO meta_consolidation_log
       (run_at, episodes_processed, notes_created, duration_ms)
     VALUES (?, ?, ?, ?)`,
  ).run(nowISO(), entry.episodesProcessed, entry.insightsCreated, entry.durationMs);
}

// ─── Internal type for raw LLM output ────────────────────────────────────────

interface RawInsight {
  type: string;
  decision: string;
  context: string;
  outcome: string;
  root_cause: string;
  lesson: string;
  domain: string;
  confidence: number;
  episode_refs: string[];
}
