import type { Thread, Message } from './types.js'

export const mockThreads: Thread[] = [
  {
    id: 1327,
    name: 'Main',
    lastMessage: 'All 3 active threads are healthy.',
    lastMessageTime: '19:24',
    unread: 0,
    isOnline: true,
  },
  {
    id: 20787,
    name: 'Alternative UI',
    lastMessage: 'Working on the chat UI mockup...',
    lastMessageTime: '19:35',
    unread: 2,
    isOnline: true,
  },
  {
    id: 13967,
    name: 'Dashboard Work',
    lastMessage: 'Dashboard v3.0.28 deployed.',
    lastMessageTime: '16:40',
    unread: 0,
    isOnline: false,
  },
  {
    id: 9790,
    name: 'Memory Audit',
    lastMessage: 'Pruning complete. 112 duplicates removed.',
    lastMessageTime: '14:15',
    unread: 0,
    isOnline: false,
  },
  {
    id: 3868,
    name: 'Narrative Pipeline',
    lastMessage: 'Quarterly reports regenerated.',
    lastMessageTime: 'Yesterday',
    unread: 0,
    isOnline: false,
  },
]

const stickerPlaceholder = 'data:image/svg+xml;base64,' + btoa(`<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160" viewBox="0 0 160 160"><rect width="160" height="160" rx="16" fill="#1a1f2e"/><circle cx="60" cy="70" r="8" fill="#e5c07b"/><circle cx="100" cy="70" r="8" fill="#e5c07b"/><path d="M55 100 q25 20 50 0" stroke="#e5c07b" stroke-width="4" fill="none" stroke-linecap="round"/><circle cx="80" cy="80" r="55" stroke="#e5c07b" stroke-width="3" fill="none"/></svg>`)

const videoNotePlaceholder = 'data:image/svg+xml;base64,' + btoa(`<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200" viewBox="0 0 200 200"><circle cx="100" cy="100" r="98" fill="#182533" stroke="#2b5278" stroke-width="3"/><polygon points="85,65 85,135 140,100" fill="#6ab3f3" opacity="0.8"/></svg>`)

const animationPlaceholder = 'data:image/svg+xml;base64,' + btoa(`<svg xmlns="http://www.w3.org/2000/svg" width="320" height="200" viewBox="0 0 320 200"><rect width="320" height="200" rx="12" fill="#0d1117"/><text x="160" y="90" text-anchor="middle" fill="#6b7c8e" font-size="14" font-family="sans-serif">GIF</text><rect x="120" y="110" width="80" height="6" rx="3" fill="#2b3845"/><rect x="120" y="110" width="50" height="6" rx="3" fill="#6ab3f3"><animate attributeName="width" values="10;80;10" dur="2s" repeatCount="indefinite"/></rect></svg>`)

const photoPlaceholder = 'data:image/svg+xml;base64,' + btoa(`<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="400" height="300" fill="#1a1f2e"/><rect x="20" y="20" width="120" height="260" rx="8" fill="#17212b" stroke="#2b3845"/><rect x="150" y="20" width="230" height="260" rx="8" fill="#0e1621" stroke="#2b3845"/><rect x="160" y="200" width="210" height="35" rx="18" fill="#242f3d"/><rect x="160" y="80" width="120" height="30" rx="12" fill="#2b5278"/><rect x="160" y="120" width="150" height="30" rx="12" fill="#182533"/><text x="200" y="155" font-family="sans-serif" font-size="11" fill="#6b7c8e">Chat UI Wireframe</text></svg>`)

export const mockMessages: Record<number, Message[]> = {
  20787: [
    {
      id: 'm1',
      threadId: 20787,
      text: 'Start remote session with sensorium. Thread name = "Alternative UI".',
      timestamp: '19:23',
      sender: 'operator',
      type: 'text',
      read: true,
    },
    {
      id: 'm2',
      threadId: 20787,
      text: 'Session resumed. Thread ID: 20787.',
      timestamp: '19:23',
      sender: 'agent',
      type: 'text',
      reactions: [{ emoji: '👍', count: 1, byMe: true }],
    },
    {
      id: 'm3',
      threadId: 20787,
      text: 'На чому ми закінчили?',
      timestamp: '19:24',
      sender: 'operator',
      type: 'text',
      read: true,
      reactions: [{ emoji: '👀', count: 1, byMe: false }],
    },
    {
      id: 'm4',
      threadId: 20787,
      text: 'Це новий тред **"Alternative UI"** — тут ми ще нічого не робили.\n\nЯкщо ти маєш на увазі загальний прогрес по наративах: ми зупинились на тому, що `quarterly` переведено в prose-формат (розповідь по ініціативах).',
      timestamp: '19:24',
      sender: 'agent',
      type: 'text',
    },
    {
      id: 'm5',
      threadId: 20787,
      text: '',
      timestamp: '19:34',
      sender: 'operator',
      type: 'voice',
      voiceDuration: 227,
      read: true,
    },
    {
      id: 'm6',
      threadId: 20787,
      text: '',
      timestamp: '19:35',
      sender: 'agent',
      type: 'voice',
      voiceDuration: 42,
      reactions: [{ emoji: '🔥', count: 1, byMe: true }],
    },
    {
      id: 'm7',
      threadId: 20787,
      text: 'Here\'s the code snippet for the transport adapter:\n\n```typescript\ninterface TransportAdapter {\n  send(threadId: number, message: string): Promise<void>\n  receive(threadId: number): AsyncGenerator<Message>\n  connect(): Promise<void>\n  disconnect(): Promise<void>\n}\n```\n\nThis is the *abstraction layer* we need. Both `TelegramAdapter` and `WebSocketAdapter` would implement this.',
      timestamp: '19:40',
      sender: 'agent',
      type: 'text',
      replyTo: { id: 'm5', sender: 'operator', text: 'Voice message about transport layer...' },
    },
    {
      id: 'm_sticker1',
      threadId: 20787,
      text: '',
      timestamp: '19:41',
      sender: 'operator',
      type: 'sticker',
      stickerEmoji: '👍',
      stickerUrl: stickerPlaceholder,
      read: true,
    },
    {
      id: 'm8',
      threadId: 20787,
      text: '',
      timestamp: '19:42',
      sender: 'agent',
      type: 'photo',
      photoUrl: photoPlaceholder,
    },
    {
      id: 'm_videonote1',
      threadId: 20787,
      text: '',
      timestamp: '19:43',
      sender: 'operator',
      type: 'video_note',
      videoNoteUrl: videoNotePlaceholder,
      videoNoteDuration: 15,
      read: true,
    },
    {
      id: 'm_gif1',
      threadId: 20787,
      text: '',
      timestamp: '19:44',
      sender: 'agent',
      type: 'animation',
      animationUrl: animationPlaceholder,
    },
    {
      id: 'm9',
      threadId: 20787,
      text: '',
      timestamp: '19:45',
      sender: 'operator',
      type: 'file',
      read: true,
      file: {
        name: 'requirements-spec.pdf',
        size: 245760,
        type: 'application/pdf',
      },
    },
    {
      id: 'm10',
      threadId: 20787,
      text: 'Got it. I\'ll review the spec and implement accordingly.',
      timestamp: '19:46',
      sender: 'agent',
      type: 'text',
      reactions: [{ emoji: '👍', count: 1, byMe: true }, { emoji: '🎉', count: 1, byMe: false }],
      replyTo: { id: 'm9', sender: 'operator', text: 'requirements-spec.pdf' },
      pinned: true,
    },
    {
      id: 'm11',
      threadId: 20787,
      text: 'Updated the ~~old approach~~ with a new **pattern-based** solution.',
      timestamp: '19:48',
      sender: 'agent',
      type: 'text',
      edited: true,
    },
  ],
  1327: [
    {
      id: 'main1',
      threadId: 1327,
      text: 'Good morning. Check threads health.',
      timestamp: '09:00',
      sender: 'operator',
      type: 'text',
      read: true,
    },
    {
      id: 'main2',
      threadId: 1327,
      text: 'All **3 active threads** are healthy. No stale sessions detected.\n\n- Thread 1327: `active` (uptime 4h 23m)\n- Thread 20787: `active` (uptime 2m)\n- Thread 13967: `dormant`',
      timestamp: '09:01',
      sender: 'agent',
      type: 'text',
    },
  ],
  13967: [
    {
      id: 'dash1',
      threadId: 13967,
      text: 'Focus on the Threads tab today.',
      timestamp: '16:30',
      sender: 'operator',
      type: 'text',
      read: true,
    },
    {
      id: 'dash2',
      threadId: 13967,
      text: 'Dashboard v3.0.28 deployed. Fixed `getRootThreads` to exclude archived threads from daily rotations.',
      timestamp: '16:40',
      sender: 'agent',
      type: 'text',
    },
  ],
  9790: [],
  3868: [],
}
